### ISSUE TITLE
Pose not detected. Timer is not starting!

### ISSUE THREAD

**Issue by maimoonakhan099** [cris-maillo/yogAI#2]
Hi! I just downloaded this application and I ran the code. I clicked on the learn and practice option and made a pose but the application was not starting the timer. Even though the pose was correct and I did it according to the system.
Please tell me what should I do so the clock can start ticking when I do the pose.

**Comment by harry040219** [comment]
Pose not detected. Timer is not starting! 
I also found this issue.

**Comment by cris-maillo** [comment]
Hi! 
Thank you both for bringing this up. I have quickly tried the app and I have personally had no issues. I would love to look into this issue in more depth but I am currently dealing with other pressing commitments. 
My only suggestion would be to ensure that your entire body is seen by the camera feed and that your room is well lit!

**Comment by cris-maillo** [comment]
@maimoonakhan099 have you tried the application directly from my deployed website (https://cris-maillo.github.io/yogAI/)?

**Comment by AbdielGaitan** [comment]
I have the same problem, I ran the code and the aplication was not starting the timer. I do not know if you can reupload the code again but with the problem resolved, i would be grateful so much, please c:

**Comment by mahanthesh0r** [comment]
Was anyone able to resolve this? I'm facing the same issue

**Comment by haeirene** [comment]
For those who have this problem, you need to open the site through a server.

If you use Visual Studio Code, you can normally find a button "Go live" (I'm not 100% certain if you need to download a plugin).

If you use atom, you need to do the following:
In atom go to file > settings > install > install the package 'atom-live-server'.
Once downloaded, you can go to packages > atom-live-server > start server.

Once the site is opened automatically in the browser, you can use the code and won't see that problem again ;)

**Comment by mahanthesh0r** [comment]
It's working for me now, The issue was that the body was not entirely visible on the camera feed. @cris-maillo Thanks for the suggestion. 👍

**Comment by cris-maillo** [comment]
@haeirene yes, good point! I probably should have mentioned that if you download and run code, the model only works through a server and yeah, the Live Server plugin on VS Code is probably the easiest way to try it out. thanks!
and for those using the website just make sure your body is visible and that the room is well lit :)
